# Generated by Django 4.1 on 2022-08-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_alter_chamado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='assunto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
